//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectMessages
    {
        public int DirectMessageID { get; set; }
        public int SenderID { get; set; }
        public int ReceiverID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Content { get; set; }
        public int ConversationID { get; set; }
    
        public virtual Conversations Conversations { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
