//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TwitterDBEntities : DbContext
    {
        public TwitterDBEntities()
            : base("name=TwitterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conversations> Conversations { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<DirectMessages> DirectMessages { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<FavoriteTweets> FavoriteTweets { get; set; }
        public virtual DbSet<Mentions> Mentions { get; set; }
        public virtual DbSet<Retweets> Retweets { get; set; }
        public virtual DbSet<Tweets> Tweets { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersFollowing> UsersFollowing { get; set; }
    
        public virtual ObjectResult<tsp_AllTweets_Result> tsp_AllTweets(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_AllTweets_Result>("tsp_AllTweets", userIDParameter);
        }
    
        public virtual ObjectResult<tsp_AllTweetsEveryone_Result> tsp_AllTweetsEveryone()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_AllTweetsEveryone_Result>("tsp_AllTweetsEveryone");
        }
    
        public virtual ObjectResult<tsp_Engagements_Result> tsp_Engagements(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_Engagements_Result>("tsp_Engagements", userIDParameter);
        }
    
        public virtual ObjectResult<tsp_FavoriteTweets_Result> tsp_FavoriteTweets(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_FavoriteTweets_Result>("tsp_FavoriteTweets", userIDParameter);
        }
    
        public virtual ObjectResult<tsp_getConversationDM_Result> tsp_getConversationDM(Nullable<int> conversationID)
        {
            var conversationIDParameter = conversationID.HasValue ?
                new ObjectParameter("conversationID", conversationID) :
                new ObjectParameter("conversationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_getConversationDM_Result>("tsp_getConversationDM", conversationIDParameter);
        }
    
        public virtual ObjectResult<tsp_GetTweet_Result> tsp_GetTweet(Nullable<int> tweetID)
        {
            var tweetIDParameter = tweetID.HasValue ?
                new ObjectParameter("tweetID", tweetID) :
                new ObjectParameter("tweetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_GetTweet_Result>("tsp_GetTweet", tweetIDParameter);
        }
    
        public virtual ObjectResult<tsp_LatestMessage_Result> tsp_LatestMessage(Nullable<int> user1ID, Nullable<int> user2ID)
        {
            var user1IDParameter = user1ID.HasValue ?
                new ObjectParameter("user1ID", user1ID) :
                new ObjectParameter("user1ID", typeof(int));
    
            var user2IDParameter = user2ID.HasValue ?
                new ObjectParameter("user2ID", user2ID) :
                new ObjectParameter("user2ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_LatestMessage_Result>("tsp_LatestMessage", user1IDParameter, user2IDParameter);
        }
    
        public virtual ObjectResult<tsp_ReplyCount_Result> tsp_ReplyCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_ReplyCount_Result>("tsp_ReplyCount");
        }
    
        public virtual ObjectResult<tsp_UserLikedTweets_Result> tsp_UserLikedTweets(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_UserLikedTweets_Result>("tsp_UserLikedTweets", userIDParameter);
        }
    
        public virtual ObjectResult<tsp_UserMentions_Result> tsp_UserMentions(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_UserMentions_Result>("tsp_UserMentions", userIDParameter);
        }
    
        public virtual ObjectResult<tsp_UserTweets_Result> tsp_UserTweets(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_UserTweets_Result>("tsp_UserTweets", userIDParameter);
        }
    
        public virtual ObjectResult<tsp_WordCount_Result> tsp_WordCount(string word)
        {
            var wordParameter = word != null ?
                new ObjectParameter("word", word) :
                new ObjectParameter("word", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tsp_WordCount_Result>("tsp_WordCount", wordParameter);
        }
    }
}
