//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersFollowing
    {
        public int FollowingID { get; set; }
        public int FollowerID { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
